### ISSUE TITLE
Issue generating SMILES in second iteration

### ISSUE THREAD

**Issue by Kcomassi** [batistagroup/ChemSpaceAL#11]
Sorry, its me again. I am having issues still and i would like to give it one more go. So i have followed the steps carefully, tried multiple times but for me the next iteration (the step of generating new smiles, this takes 2 hours to generate 100 smiles on the L4 GPU), not sure where the issue would lie. To sample 1000 molecules what number of clusters and samples per cluster would be good? Generating a 100.000 SMILES at this rate is not possible of course so i tried it with a smaller sample and the results were not good ( a lot had a score of 0) so something is going wrong somewhere.

**Comment by anmorgunov** [comment]
No need to apologize. Such low speed is an indication that something is wrong with the model, so it doesn't make a lot of sense to continue with the pipeline. Can you check/share the losses you get during fine tuning? They should look roughly like this:

![image](https://github.com/user-attachments/assets/e7836bbc-580d-4684-b60d-4ea8056ab27b)

If it doesn't look like this, can you go to "1_Pretraining/dataset_descriptors", remove combined_train.yaml, then run Cell 4 with downloadModelWeights set to True (that flag also gets you those descriptors), and try running fine tuning again?

**Comment by Kcomassi** [comment]
wow, that did the trick together with increasing the amount of epochs! thank you for your help again!

**Comment by anmorgunov** [comment]
glad it works, feel free to raise other issues if something else is not working
