### ISSUE TITLE
Preprocessing PDB files

### ISSUE THREAD

**Issue by Kcomassi** [batistagroup/ChemSpaceAL#12]
When running the pipeline for other molecules I have issues when scoring the docked molecules and get errors like:   63%|██████▎   | 627/999 [27:50<16:38,  2.68s/it][21:11:57] Explicit valence for atom # 8 N, 4, is greater than permitted
[21:11:57] ERROR: Could not sanitize molecule ending on line 53
[21:11:57] ERROR: Explicit valence for atom # 8 N, 4, is greater than permitted
It appears some preprocessing of the pdb files is needed, what do you do when downloading new pdb files?

**Comment by anmorgunov** [comment]
we did some pre-processing on the pdb file: added hydrogens, removed water & salt ions. Not sure if that could affect the issue you have, but I also can't tell where it'd come from as only valid smiles are kept during generation. Hope this helps

**Comment by Kcomassi** [comment]
Thank you for your response! And i agree, that is why i didnt understand, since only valid smiles are kept. It works great on the two pdb files that you provide, but when trying different pdb files the pipeline doesnt work so far. The problem is always when scoring the complexes. I was wondering if you tried it for different pdb files yet?

**Comment by Kcomassi** [comment]
Thank you for your response, it works now!
