### ISSUE TITLE
Example Noebook Error

### ISSUE THREAD

**Issue by satvikkg** [batistagroup/ChemSpaceAL#5]
Hi, I was trying to run the example google colab notebook and I came across the following error:
The error is raised for the following cell:
# model objects and trainer objects are returned in case you want to do something with them
model, trainer = Training.train_GPT(
    config=config,
    training_dataset=datasets[0],
    validation_dataset=datasets[1]
)
And the error is:
epoch 1 iter 0: train loss 3.01657. lr 3.000000e-05: 100%|██████████| 1/1 [00:01<00:00,  1.37s/it]

---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

[<ipython-input-9-f348524cbe3e>](https://localhost:8080/#) in <cell line: 2>()
      1 # model objects and trainer objects are returned in case you want to do something with them
----> 2 model, trainer = Training.train_GPT(
      3     config=config,
      4     training_dataset=datasets[0],
      5     validation_dataset=datasets[1]

1 frames

[/usr/local/lib/python3.10/dist-packages/ChemSpaceAL/Training.py](https://localhost:8080/#) in train(self)
    143 
    144             if self.valid_dataset is not None:
--> 145                 valid_loss = self.run_epoch("valid")
    146                 log_dict["epoch_valid_loss"] = valid_loss
    147 

TypeError: Trainer.run_epoch() missing 1 required positional argument: 'epoch'

Solution for the error will be highly appreciated

**Comment by AdrienCerdan** [comment]
same !

**Comment by ByteTora** [comment]
same!

**Comment by anmorgunov** [comment]
Hello everyone! Sorry for such a delay @satvikkg.

I've pushed a fix to this issue, and I double-checked that the code now runs without an error, but please let me know if this works for you or not!

**Comment by anmorgunov** [comment]
I'm going to close this issue, but please feel free to start new one if you need any other help!
